// Code generated by tmjson. DO NOT EDIT

package sr25519

import (
	"encoding/json"
	"fmt"
)

var _ fmt.Stringer // suppress unused package

type _typeTagged struct {
	T string          `json:"type"`
	V json.RawMessage `json:"value"`
}

const _typeTag_PubKey = "tendermint/PubKeySr25519"

// MarshalJSON implements the json.Marshaler interface for PubKey.
// It wraps the encoding in a type-tagged object.
func (v PubKey) MarshalJSON() ([]byte, error) {
	type shim PubKey
	value, err := json.Marshal((*shim)(&v))
	if err != nil {
		return nil, err
	}
	return json.Marshal(_typeTagged{T: _typeTag_PubKey, V: value})
}

const _typeTag_PrivKey = "tendermint/PrivKeySr25519"

// MarshalJSON implements the json.Marshaler interface for PrivKey.
// It wraps the encoding in a type-tagged object.
func (v PrivKey) MarshalJSON() ([]byte, error) {
	type shim PrivKey
	value, err := json.Marshal((*shim)(&v))
	if err != nil {
		return nil, err
	}
	return json.Marshal(_typeTagged{T: _typeTag_PrivKey, V: value})
}
