// Code generated by tagtype. DO NOT EDIT.

package sr25519

import (
	"encoding/json"
	"fmt"
)

type __jsonWrapper__ struct {
	T string          `json:"type"`
	V json.RawMessage `json:"value"`
}

// MarshalJSON implements the json.Marshaler interface for PrivKey.
// It encodes the value as a tagged wrapper object.
func (v PrivKey) MarshalJSON() ([]byte, error) {
	type shim PrivKey
	data, err := json.Marshal((*shim)(&v))
	if err != nil {
		return nil, err
	}
	return json.Marshal(__jsonWrapper__{
		T: v.jsonWrapperTag(), V: data,
	})
}

// UnmarshalJSON implements the json.Unmarshaler interface for PrivKey.
// It expects a tagged wrapper object containing the encoded value.
func (v *PrivKey) UnmarshalJSON(data []byte) error {
	var wrapper __jsonWrapper__
	if err := json.Unmarshal(data, &wrapper); err != nil {
		return err
	} else if want := v.jsonWrapperTag(); wrapper.T != want {
		return fmt.Errorf("type tag %q does not match %q", wrapper.T, want)
	}
	type shim PrivKey
	return json.Unmarshal(wrapper.V, (*shim)(v))
}

// MarshalJSON implements the json.Marshaler interface for PubKey.
// It encodes the value as a tagged wrapper object.
func (v PubKey) MarshalJSON() ([]byte, error) {
	type shim PubKey
	data, err := json.Marshal((*shim)(&v))
	if err != nil {
		return nil, err
	}
	return json.Marshal(__jsonWrapper__{
		T: v.jsonWrapperTag(), V: data,
	})
}

// UnmarshalJSON implements the json.Unmarshaler interface for PubKey.
// It expects a tagged wrapper object containing the encoded value.
func (v *PubKey) UnmarshalJSON(data []byte) error {
	var wrapper __jsonWrapper__
	if err := json.Unmarshal(data, &wrapper); err != nil {
		return err
	} else if want := v.jsonWrapperTag(); wrapper.T != want {
		return fmt.Errorf("type tag %q does not match %q", wrapper.T, want)
	}
	type shim PubKey
	return json.Unmarshal(wrapper.V, (*shim)(v))
}
